Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Tutorial1.Models
{
    public class Appointment
    {
        [Key]
        public int Id { get; set; }
        public int DoctorId { get; set; }
        [Required]
        [MinLength(3)]
        public string Diagnose { get; set; }
        [Required]
        [MinLength(3)]
        public string Complaints { get; set; }
        [DisplayName("Date of visit")]
        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOfVisit { get; set; }
        public int PatientId { get; set; }

        [NotMapped]
        [Required]
        [DisplayName("Doctor's name")]
        public string DoctorName { get; set; }
        [NotMapped]
        [DisplayName("Patient's name")]
        [Required]
        public string PatientName { get; set; }
    }
}

Models/AppointmentViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tutorial1.Models
{
    public class AppointmentViewModel
    {
        public Appointment appointment { get; set; }
        public List<Appointment> appointments { get; set; }
        public SelectList doctors { get; set; }
        public SelectList patients { get; set; }
        public string DoctorId { get; set; }
        public string PatientId { get; set; }
        public string Diagnose { get; set; }
        [Required]
        public string Complaints { get; set; }
        [DisplayName("Date of visit")]
        [Required]
        public DateTime DateOfVisit { get; set; }
    }
}

Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tutorial1.Models
{
    public class Doctor
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Speciality { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Tutorial1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tutorial1.Models
{
    public class Patient
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public double IIN { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
        [Required]
        [StringLength(30)]
        public string Surname { get; set; }
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Address { get; set; }
        [RegularExpression(@"/\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/")]
        [Required]
        public string PhoneNumber { get; set; }
    }
}

Models/PatientViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tutorial1.Models
{
    public class PatientViewModel
    {
        public Patient patient { get; set; }
        public List<Patient> patients { get; set; }
    }
}

Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Tutorial1.Data;
using Tutorial1.Models;


namespace Tutorial1.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly AppDbContext _db;

        public AppointmentController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Create()
        {
            AppointmentViewModel model = new AppointmentViewModel();
            model.appointment = new Appointment();
            model.appointments = _db.Appointments.ToList();
            model.doctors = new SelectList(_db.Doctors, "Id", "Name");
            model.patients = new SelectList(_db.Patients, "Id", "Name");

            foreach (var visit in model.appointments)
            {
                visit.PatientName = _db.Patients.Where(x => x.Id == visit.PatientId).Select(x => x.Name).FirstOrDefault();
                visit.DoctorName = _db.Doctors.Where(x => x.Id == visit.DoctorId).Select(x => x.Name).FirstOrDefault();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AppointmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                Appointment app = new Appointment();
                app.PatientId = Convert.ToInt32(model.PatientId);
                app.Complaints = model.Complaints;
                app.DoctorId = Convert.ToInt32(model.DoctorId);
                app.Diagnose = model.Diagnose;
                app.DateOfVisit = model.DateOfVisit;
                _db.Appointments.Add(app);
                _db.SaveChanges();
                return View();
            }
            else
            {
                AppointmentViewModel models = new AppointmentViewModel();
                Appointment app = new Appointment();
                app.PatientId = Convert.ToInt32(model.PatientId);
                app.Complaints = model.Complaints;
                app.DoctorId = Convert.ToInt32(model.DoctorId);
                app.Diagnose = model.Diagnose;
                app.DateOfVisit = model.DateOfVisit;
                models.appointment = app;
                models.appointments = _db.Appointments.ToList();
                models.doctors = new SelectList(_db.Doctors, "Id", "Name");
                models.patients = new SelectList(_db.Patients, "Id", "Name");

                foreach (var visit in models.appointments)
                {
                    visit.PatientName = _db.Patients.Where(x => x.Id == visit.PatientId).Select(x => x.Name).FirstOrDefault();
                    visit.DoctorName = _db.Doctors.Where(x => x.Id == visit.DoctorId).Select(x => x.Name).FirstOrDefault();
                }
                ModelState.AddModelError("ReviewErrors", "some error occured");
                return View(models);
            }
        }

        public IActionResult Delete(int id)
        {
            var appointment = _db.Appointments.Where(x => x.Id == id).FirstOrDefault();
            _db.Appointments.Remove(appointment);
            _db.SaveChanges();
            return RedirectToAction("Create");
        }
    }
}

Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tutorial1.Data;
using Tutorial1.Models;

namespace Tutorial1.Controllers
{
    public class PatientController : Controller
    {
        private readonly AppDbContext _db;

        public PatientController(AppDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Create()
        {
            PatientViewModel model = new PatientViewModel();
            model.patient = new Patient();
            model.patients = _db.Patients.ToList();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Patient patient)
        {
            if (ModelState.IsValid)
            {
                _db.Patients.Add(patient);
                _db.SaveChanges();
                return View();
            }
            else
            {
                ModelState.AddModelError("ReviewErrors", "some error occured");
                PatientViewModel model = new PatientViewModel();
                model.patient = patient;
                model.patients = _db.Patients.ToList();
                return View(model);
            }
        }

        public IActionResult Delete(int id)
        {
            var patient = _db.Patients.Where(x => x.Id == id).FirstOrDefault();
            _db.Patients.Remove(patient);
            _db.SaveChanges();
            return RedirectToAction("Create");
        }
    }
}

Views/Appointment/Create.cshtml
@using Tutorial1;
@model AppointmentViewModel
@{
    ViewData["Title"] = "Appointment Page";
}

<div class="container p-0">
    <div class="row pt-2">
        <div class="col-8">
            <h2 class="text-primary">Appointments</h2>
        </div>
        <div class="col-4">
            <h2 class="text-primary">Create new Appointment</h2>
        </div>
        <br />

        <div class="col-8">
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            Doctor Name
                        </th>
                        <th>
                            Diagnose
                        </th>
                        <th>
                            Complaints
                        </th>
                        <th>
                            Date Of Visit
                        </th>
                        <th>
                            Patient Name
                        </th>
                        <th>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.appointments)
                    {
                        <tr>
                            <td width="20%">@item.DoctorName</td>
                            <td width="20%">@item.Diagnose</td>
                            <td width="20%">@item.Complaints</td>
                            <td width="20%">@item.DateOfVisit</td>
                            <td width="20%">@item.PatientName</td>
                            <td width="20%">
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
        <div class="col-4">
            <br />
            <br />
            <div class="container" id="tohide">
                <form method="post" asp-action="Create">
                    <div class="border p-3">
                        @Html.ValidationSummary(true)
                        <div class="form-group row">
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="appointment.DoctorName"></label>
                                    </div>
                                    <div class="col-6">
                                        @Html.DropDownListFor(m => m.DoctorId, Model.doctors as SelectList)
                                        @Html.ValidationMessageFor(x => x.appointment.DoctorName)
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="appointment.PatientName"></label>
                                    </div>
                                    <div class="col-6">
                                        @Html.DropDownListFor(m => m.PatientId, Model.patients as SelectList)
                                        @Html.ValidationMessageFor(x => x.appointment.PatientName)
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="Diagnose"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="Diagnose" class="form-control" />
                                        <span asp-validation-for="appointment.Diagnose" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="Complaints"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="Complaints" class="form-control" />
                                        <span asp-validation-for="appointment.Complaints" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="DateOfVisit"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="DateOfVisit" id="datepicker" class="form-control"
                                               value="@DateTime.Now.ToString("yyyy-MM-ddThh:mm")" />
                                        <span asp-validation-for="DateOfVisit" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-8 row">
                                        <div class="col">
                                            <input type="submit" class="btn btn-info w-100" value="Create" />
                                        </div>
                                        <br />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
}

Views/Patient/Create.cshtml
@model PatientViewModel
@{
    ViewData["Title"] = "Patient Page";
}

<div class="container p-0">
    <div class="row pt-2">
        <div class="col-8">
            <h2 class="text-primary">Patients</h2>
        </div>
        <div class="col-4">
            <h2 class="text-primary">Create new Patient</h2>
        </div>
        <br />

        <div class="col-8">
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            IIN
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Surname
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            PhoneNumber
                        </th>
                        <th>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.patients)
                    {
                        <tr>
                            <td width="20%">@item.IIN</td>
                            <td width="20%">@item.Name</td>
                            <td width="20%">@item.Surname</td>
                            <td width="20%">@item.Address</td>
                            <td width="20%">@item.PhoneNumber</td>
                            <td width="20%">
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-4">
            <br />
            <br />
            <div class="container" id="tohide">
                <form method="post" asp-action="Create">
                    <div class="border p-3">
                        @Html.ValidationSummary(true)
                        <div class="form-group row">
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="patient.IIN"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="patient.IIN" class="form-control" />
                                        <span asp-validation-for="patient.IIN" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="patient.Name"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="patient.Name" class="form-control" />
                                        <span asp-validation-for="patient.Name" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="patient.Surname"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="patient.Surname" class="form-control" />
                                        <span asp-validation-for="patient.Surname" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="patient.Address"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="patient.Address" class="form-control" />
                                        <span asp-validation-for="patient.Address" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label asp-for="patient.PhoneNumber"></label>
                                    </div>
                                    <div class="col-6">
                                        <input asp-for="patient.PhoneNumber" class="form-control" />
                                        <span asp-validation-for="patient.PhoneNumber" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-8 row">
                                        <div class="col">
                                            <input type="submit" class="btn btn-info w-100" value="Create" />
                                        </div>
                                        <br />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Appointment" asp-action="Index">HospitalDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Create">Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Create">Patients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HospitalDemo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>